local separator = require("separator")

require("items.aerospace")
require("items.front_app")
require("items.calendar")
separator.add("clock", 1)
require("items.battery")
require("items.volume")
require("items.keyboard")
separator.add("system", 1)
require("items.spotify")
require("items.service_status")
require("items.ai_usage")
require("items.herdr")
