vim.diagnostic.config({ signs = false })

vim.lsp.enable({
	"bashls",
	"clangd",
	"gopls",
	"golangci_lint_ls",
	"lua_ls",
	"stylua",
	"taplo",
	"tofu_ls",
	"zizmor",
	"jsonls",
	"nixd",
	"rust_analyzer",
	"yamlls",
	"buf_ls",
	"copilot",
	"basedpyright",
	"ruff",
	"harper",
	"gdscript",
})

-- Servers that only exist when a feature installs them.
-- Generated by home/packages/shell/neovim.nix.
pcall(require, "lsp-features")
