#!/usr/bin/env bash

set -euo pipefail

# Go to git repository root

readonly old_pwd="$PWD"
while [[ 1 ]]; do
    cd ..
    if [[ "$PWD" == "/" ]]; then
        cd "$old_pwd"
        echo "No repository found, returned to $PWD"
        return 1
    fi
    for repo in ".git" ".hg"; do
        if [[ -d "$repo" ]]; then
            echo "Found $repo at $PWD"
            return 0
        fi
    done
done
