#!/usr/bin/env bash

set -euo pipefail

# Check if we are in arepo with git rev-parse --is-inside-work-tree
if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  echo "Not in a git repository"
  exit 1
fi

cd "$(git rev-parse --show-toplevel)"
