{
  config,
  lib,
  pkgs,
  neovimPackage,
  ...
}: let
  # Servers whose binary only arrives with a feature. Enabling one without its
  # binary leaves nvim reporting a server that cannot start.
  featureServers =
    lib.optionals (config.features.js == "full") ["ts_ls" "eslint"]
    ++ lib.optionals config.features.web3 ["solidity_ls"]
    ++ lib.optionals config.features.dart ["dartls"];
in {
  programs.neovim = {
    enable = lib.mkDefault true;
    package = neovimPackage;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    vimdiffAlias = true;
    extraPackages = with pkgs; [
      tree-sitter
      copilot-language-server # for "copilotlsp" neovim plugin
      bash-language-server
      shellcheck
      shfmt
      harper
      yaml-language-server
      vscode-langservers-extracted # vscode-json-language-server
      # TODO: lsp formatting and linters
      # codespell
      # yamlfmt
      # zizmor
      # wgsl-analyzer
    ];
  };

  home.file.".config/nvim/lua/lsp-features.lua".text = ''
    -- Generated by home/packages/shell/neovim.nix from config.features.
    vim.lsp.enable({
    ${lib.concatMapStringsSep "\n" (name: "\t\"${name}\",") featureServers}
    })
  '';
}
