{
  config,
  lib,
  pkgs,
  neovimPackage,
  ...
}: let
  # Servers that are not the same on every machine: either the binary only
  # arrives with a feature, or the machine wants a different server for the
  # same language. The work Mac reads this list through a chezmoi template.
  featureServers =
    ["tofu_ls"]
    ++ lib.optionals (config.features.js == "minimal" || config.features.js == "full") ["ts_ls"]
    ++ lib.optionals (config.features.js == "full") ["eslint"];
in {
  programs.neovim = {
    enable = lib.mkDefault true;
    package = neovimPackage;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    vimdiffAlias = true;
    extraPackages = with pkgs; [
      tree-sitter
      copilot-language-server # for "copilotlsp" neovim plugin
      bash-language-server
      shellcheck
      shfmt
      harper
      yaml-language-server
      vscode-langservers-extracted # vscode-json-language-server
      tofu-ls
      zizmor
      # TODO: lsp formatting and linters
      # codespell
      # yamlfmt
      # wgsl-analyzer
    ];
  };

  home.file.".config/nvim/lua/lsp-features.lua".text = ''
    -- Generated by home/packages/shell/neovim.nix from config.features.
    vim.lsp.enable({
    ${lib.concatMapStringsSep "\n" (name: "\t\"${name}\",") featureServers}
    })
  '';
}
