{
  config,
  lib,
  pkgs,
  neovimPackage,
  ...
}: {
  programs.neovim = {
    enable = lib.mkDefault true;
    package = neovimPackage;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    vimdiffAlias = true;
    extraPackages = with pkgs; [
      tree-sitter
      copilot-language-server # for "copilotlsp" neovim plugin
      bash-language-server
      shellcheck
      shfmt
      harper
      yaml-language-server
      vscode-langservers-extracted # vscode-json-language-server
      tofu-ls
      zizmor
      # TODO: lsp formatting and linters
      # codespell
      # yamlfmt
      # wgsl-analyzer
    ];
  };

  # The servers extraPackages installs.
  dotfiles.neovim.lspServers = ["bashls" "harper_ls" "jsonls" "tofu_ls" "yamlls" "zizmor"];

  home.file.".config/nvim/lua/lsp-servers.lua".text = ''
    -- Generated by home/packages/shell/neovim.nix from dotfiles.neovim.lspServers.
    vim.lsp.enable({
    ${lib.concatMapStringsSep "\n" (name: "\t\"${name}\",") (lib.naturalSort (lib.unique config.dotfiles.neovim.lspServers))}
    })
  '';
}
