onboarding = false

[theme]
name = "terminal"
auto_switch = false

[theme.custom]
accent = "gray"
active_row_bg = "#222222"
pane_active_border = "gray"
pane_inactive_border = "darkgray"
tab_active_bg = "#000000"
tab_active_fg = "white"
tab_inactive_bg = "#000000"
tab_inactive_fg = "darkgray"

[keys]
prefix = "ctrl+b"
reload_config = "prefix+r"
resize_mode = "prefix+shift+r"
detach = "prefix+d"
rename_workspace = "prefix+$"
rename_tab = "prefix+,"
previous_tab = ["prefix+p", "prefix+ctrl+p"]
next_tab = ["prefix+n", "prefix+ctrl+n"]
last_pane = "prefix+tab"
split_vertical = "prefix+%"
split_horizontal = 'prefix+"'
focus_pane_left = "ctrl+h"
focus_pane_down = "ctrl+j"
focus_pane_up = "ctrl+k"
focus_pane_right = "ctrl+l"
passthrough_commands = ["nvim"]
navigate_workspace_up = "k"
navigate_workspace_down = "j"
navigate_pane_up = "up"
navigate_pane_down = "down"
previous_agent = "prefix+["
next_agent = "prefix+]"
new_worktree = "prefix+shift+t"
open_worktree = "prefix+shift+w"
next_workspace = "prefix+j"
previous_workspace = "prefix+k"

[ui]
sidebar_collapsed_mode = "hidden"
confirm_close = true
prompt_new_tab_name = false
prompt_new_workspace_name = false
pane_borders = true
pane_outer_borders = false
pane_gaps = false
hide_tab_bar_when_single_tab = false
pane_scrollbars = false
tab_bar_position = "bottom"
show_agent_labels_on_pane_borders = false
agent_panel_sort = "spaces"
prefix_hint = false
mobile_width_threshold = 68
detach_effect = "matrix"
detach_effect_ms = 800

[ui.toast]
delivery = "off"

[ui.sound]
enabled = true

[ui.sidebar.spaces]
rows = [
  ["state_icon", "workspace", "git_status"],
]

[ui.sidebar.agents]
rows = [
    ["state_icon", "machine", { token = "workspace", fg = "#bbbbbb" }, "spacer", "tab"]
]

[experimental]
pane_history = false

[ui.sidebar.machines]
agent_token = "icon"
hide_agents_when_collapsed = true

[ui.sidebar.machines.labels]
local = { icon = " ", name = "mbp"}
andromeda = { icon = " ", name = "andromeda"}
work = { icon =  "󰃖 ", name = "work"}
