local canvas = require("canvas")

local M = {}

-- hs.settings is NSUserDefaults, so the history survives reloads and restarts
local KEY = "clipboard.history"
local LIMIT = 200
local POLL = 0.4

-- Anything above this is a file's worth of text rather than something to paste
-- again, and NSUserDefaults is the wrong place to keep it. Dropped, not cut:
-- half a payload pasted back would be worse than not having it.
local MAX_LENGTH = 100000

-- the marker types every password manager writes, rbw.lua included. A secret
-- must never reach the history, so the watcher lets these pass unread.
local IGNORED_TYPES = {
	["org.nspasteboard.ConcealedType"] = true,
	["org.nspasteboard.TransientType"] = true,
	["org.nspasteboard.AutoGeneratedType"] = true,
}

local timer = nil
local lastChange = nil
local paused = false

local function history()
	return hs.settings.get(KEY) or {}
end

local function isIgnored()
	for _, kind in ipairs(hs.pasteboard.contentTypes() or {}) do
		if IGNORED_TYPES[kind] then
			return true
		end
	end

	return false
end

local function record()
	local text = hs.pasteboard.getContents()

	if type(text) ~= "string" or text:match("^%s*$") or #text > MAX_LENGTH then
		return
	end

	local entries = history()

	-- copied again, an entry moves back to the top rather than appearing twice
	for i, entry in ipairs(entries) do
		if entry.text == text then
			table.remove(entries, i)
			break
		end
	end

	table.insert(entries, 1, { text = text, at = os.time() })

	while #entries > LIMIT do
		table.remove(entries)
	end

	hs.settings.set(KEY, entries)
end

local function poll()
	local count = hs.pasteboard.changeCount()

	if paused or count == lastChange then
		return
	end

	lastChange = count

	if not isIgnored() then
		record()
	end
end

-- Something that borrows the pasteboard rather than writing to it wraps the
-- borrowing in these, and the history never sees it. resume() takes the count
-- as it stands, so nothing that happened while paused is picked up afterwards.
function M.pause()
	paused = true
end

function M.resume()
	lastChange = hs.pasteboard.changeCount()
	paused = false
end

local function ago(at)
	local delta = os.time() - (at or 0)

	if delta < 60 then
		return "now"
	end

	if delta < 3600 then
		return math.floor(delta / 60) .. "m ago"
	end

	if delta < 86400 then
		return math.floor(delta / 3600) .. "h ago"
	end

	return math.floor(delta / 86400) .. "d ago"
end

-- one line of it, so a paragraph and a snippet of code both stay one row high
local function preview(text)
	local trimmed = text:match("^%s*(.-)%s*$")

	return (trimmed:gsub("%s+", " "))
end

local function subText(entry)
	local lines = select(2, entry.text:gsub("\n", "")) + 1
	local size = lines > 1 and (lines .. " lines") or (#entry.text .. " chars")

	return ago(entry.at) .. " · " .. size
end

local function paste(text)
	hs.pasteboard.setContents(text)

	-- the picker restores focus as it closes, and the window it hands back to
	-- needs a moment before it will take the keystroke
	hs.timer.doAfter(0.2, function()
		hs.eventtap.keyStroke({ "cmd" }, "v")
	end)
end

function M.open()
	local entries = history()

	if #entries == 0 then
		hs.alert.show("clipboard: nothing yet")
		return true
	end

	local choices = {}

	for i, entry in ipairs(entries) do
		table.insert(choices, {
			text = preview(entry.text),
			subText = subText(entry),
			value = entry.text,
			-- with no query every score is 0, so this alone orders the list by
			-- recency. Kept small so that typing puts the match back in charge.
			boost = (#entries - i) / #entries * 10,
		})
	end

	canvas.picker({
		prompt = "clipboard",
		choices = choices,
		onSelect = function(choice)
			paste(choice.value)
		end,
		-- shift+return puts it on the pasteboard without pasting it
		onAlternate = function(choice)
			hs.pasteboard.setContents(choice.value)
			hs.alert.show("clipboard: copied")
		end,
	})

	return true
end

function M.start()
	if timer then
		return M
	end

	lastChange = hs.pasteboard.changeCount()
	timer = hs.timer.doEvery(POLL, poll)

	return M
end

return M
