leader_key = "f18"
leader_key_mods = ""
auto_reload = false
show_ui = true

b = ["Firefox", "browser"]
r = ["Sol", "launcher"]
t = ["Ghostty", "terminal"]

[o]
label = "[open]"
c = ["Cursor", "cursor"]
d = ["Discord", "discord"]
e = ["eqMac", "eqmac"]
f = ["Finder", "finder"]
k = ["KeepassXC", "keepassxc"]
m = ["Activity Monitor", "monitor"]
o = ["Orbstack", "orbstack"]
p = ["System Preferences", "preferences"]
s = ["Spotify", "spotify"]

[w]
label = "[work]"
b = ["Google Chrome", "browser"]
c = ["MongoDB Compass", "compass"]
d = ["Datagrip", "datagrip"]
o = ["OpenVPN Connect", "openvpn"]
p = ["Postman", "postman"]
r = ["Redis Insight", "redis"]
s = ["Slack", "slack"]

[l]
label = "[links]"
y = ["https://www.youtube.com", "youtube"]

[l.t]
label = "[t]"
w = ["https://twitter.com", "twitter"]
3 = ["https://t3.chat", "t3"]
r = ["https://www.tradingview.com/chart/4ztWXosm", "tradingview"]

[l.g]
label = "[g]"
e = ["https://gemini.google.com", "gemini"]
o = ["https://google.com", "google"]
m = ["https://mail.google.com", "gmail"]

[l.d]
label = "[d]"
r = ["https://drive.google.com", "google drive"]

[l.w]
label = "[w]"
h = ["https://web.whatsapp.com", "whatsapp"]

[p]
label = "[paste]"
e = "text:ettali.samir@gmail.com"
u = "text:samirettali"

[s]
label = "[search]"
w = ["input:https://google.com/search?q={input}", "google"]
m = ["input:https://www.google.com/maps/search/{input}", "maps"]
n = ["input:https://mynixos.com/search?q={input}", "nixos"]
p = ["input:https://perplexity.ai/search?q={input}", "perplexity"]
y = ["input:https://www.youtube.com/results?search_query={input}", "youtube"]

[s.g]
label = "[g]"
r = ["input:https://github.com/search?q={input}&type=repositories", "github repositories"]
c = ["input:https://github.com/search?q={input}&type=code" , "github code"]
