leader_key = "space"
leader_key_mods = "cmd"
auto_reload = false
show_ui = true
use_default_alert_style = true

b = "Zen"
t = "Ghostty"
r = ["raycast://extensions/raycast", "raycast"]

[o]
label = "[open]"
c = "MongoDB Compass"
d = "Discord"
f = "Finder"
k = "KeepassXC"
m = "Activity Monitor"
o = "Orbstack"
p = "System Preferences"
s = "Spotify"
x = "Cursor"

[o.w]
label = "[work]"
b = "Google Chrome"
c = "MongoDB Compass"
d = "Datagrip"
o = "OpenVPN Connect"
p = "Postman"
r = "Redis Insight"
s = "Slack"

[a]
label = "[actions]"
e = ["raycast://extensions/raycast/emoji-symbols/search-emoji-symbols", "emoji picker"]
p = "shortcut:cmd shift 2"

[a.s]
label = "[spotify]"
n = ["hs:hs.spotify.next()", "next"]
p = ["hs:hs.spotify.previous()", "previous"]
t = ["hs:hs.spotify.playpause()", "toggle play/pause"]
f = ["hs:hs.spotify.ff()", "fast forward"]
r = ["hs:hs.spotify.rw()", "rewind"]

[l]
label = "[links]"
g = "https://google.com"
t = "https://twitter.com"

[p]
label = "[prefixes]"
e = "text:ettali.samir@gmail.com"
u = "samirettali"

[s]
label = "[search]"
g = "input:https://google.com/search?q={input}"
m = "input:https://www.google.com/maps/search/{input}"
n = "input:https://mynixos.com/search?q={input}"
p = "input:https://perplexity.ai/search?q={input}"
