leader_key = "f18"
leader_key_mods = ""
auto_reload = false
show_ui = true

b = ["Firefox", "browser"]
r = ["Sol", "launcher"]
t = ["Ghostty", "terminal"]

[o]
label = "[open]"
c = ["Cursor", "cursor"]
d = ["Discord", "discord"]
e = ["eqMac", "eqmac"]
f = ["Finder", "finder"]
k = ["KeepassXC", "keepassxc"]
m = ["Activity Monitor", "monitor"]
o = ["Orbstack", "orbstack"]
p = ["System Preferences", "preferences"]
s = ["Spotify", "spotify"]

[w]
label = "[work]"
b = ["Google Chrome", "browser"]
c = ["MongoDB Compass", "compass"]
d = ["Datagrip", "datagrip"]
o = ["OpenVPN Connect", "openvpn"]
p = ["Postman", "postman"]
r = ["Redis Insight", "redis"]
s = ["Slack", "slack"]

[l]
label = "[links]"
y = ["https://www.youtube.com", "youtube"]

[l.t]
label = "[t]"
w = ["https://twitter.com", "twitter"]
3 = ["https://t3.chat", "t3"]

[l.g]
label = "[g]"
e = ["https://gemini.google.com", "gemini"]
o = ["https://google.com", "google"]

[l.d]
label = "[d]"
r = ["https://drive.google.com", "google drive"]

[p]
label = "[paste]"
e = "text:ettali.samir@gmail.com"
u = "text:samirettali"

[s]
label = "[search]"
g = "input:https://google.com/search?q={input}"
m = "input:https://www.google.com/maps/search/{input}"
n = "input:https://mynixos.com/search?q={input}"
p = "input:https://perplexity.ai/search?q={input}"
