#!/usr/bin/env python3
import facebook
import notify2
import time

# Creates a notify with the menu of the place I eat at when I'm at university
# Needs facebook-sdk and notify2 pip packages
# pip install --user facebook-sdk notify2

access_token = 'FACEBOOKAPIKEY'
user = 'selfservicedoctorino'
graph = facebook.GraphAPI(access_token)
data = graph.get_object(user)
posts = graph.get_connections(data['id'], 'posts')
date = time.strftime("%d/%m")
menu = posts['data'][0]['message']
if date not in menu:
    menu = "Non c'è ancora il menù del giorno"
notify2.init('Menu app')
n = notify2.Notification('Menù del giorno', menu, 'lol')
n.show()
