#!/usr/bin/env zsh

set -e

# This script prints the repository status of all of my projects

red='\e[31m'
green='\e[32m'
yellow='\e[33m'
blue='\e[34m'
off='\e[0m'

repositories=( "$HOME/CTF/kali-ctf" "$HOME/CTF/ctf-scripts")
unstaged_ignore=( "kali-ctf" "Blog" )
for folder in $(ls -1 $HOME/Projects); do
    if [ -d "$HOME/Projects/$folder/.git" ]; then
        repositories+="$HOME/Projects/$folder"
    else
        echo -e "$red"'[!]'"$off Projects/$folder is not a repository"
    fi
done

for repo in ${repositories[@]}; do
    repo_name=$(echo $repo | sed 's|.*/||')
    CHANGED=$(git -C $repo diff-index --name-only HEAD --)
    UNSTAGED=$(git -C $repo ls-files --others --exclude-standard)
    if [ -z $CHANGED ] && [ -z $UNSTAGED ]; then
        echo -e "$green"'[+]'"$off $repo_name is clean"
    else
        if [ $CHANGED ] && [ $UNSTAGED ]; then
            echo -e "$yellow"'[-]'"$off $repo_name has unstaged and uncommitted files"
        elif [ $UNSTAGED ]; then
            echo -e "$red"'[-]'"$off $repo_name has unstaged files"
        elif [ $CHANGES ]; then
            echo -e "$red"'[-]'"$off $repo_name has uncommitted files"
        fi
    fi
done
