ignoreGeneratedHeader = true
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 0
enableAllRules = true

[rule.exported]
Disabled = true

[rule.unhandled-error]
arguments = ["fmt.Println", "fmt.Printf"]
