#!/usr/bin/env bash

set -eu

if [[ "$1" =~ ^[^\/]*$ ]]; then
    REPO_URL="https://github.com/samirettali/${1}"
elif [[ "$1" =~ ^[^\/]*\/[^\/]*$ ]]; then
    REPO_URL="https://github.com/${1}"
else
    REPO_URL="${1}"
fi

echo $REPO_URL
git clone "${REPO_URL}" "${@:2}"
