onboarding = false

[experimental]
pane_history = false

[keys]
detach = "prefix+d"
focus_pane_down = "ctrl+j"
focus_pane_left = "ctrl+h"
focus_pane_right = "ctrl+l"
focus_pane_up = "ctrl+k"
last_pane = "prefix+tab"
navigate_pane_down = "down"
navigate_pane_up = "up"
navigate_workspace_down = "j"
navigate_workspace_up = "k"
new_worktree = "prefix+shift+t"
next_agent = "prefix+]"
next_tab = ["prefix+n", "prefix+ctrl+n"]
next_workspace = "prefix+j"
open_worktree = "prefix+shift+w"
passthrough_commands = ["nvim"]
prefix = "ctrl+b"
previous_agent = "prefix+["
previous_tab = ["prefix+p", "prefix+ctrl+p"]
previous_workspace = "prefix+k"
reload_config = "prefix+r"
rename_tab = "prefix+,"
rename_workspace = "prefix+$"
resize_mode = "prefix+shift+r"
split_horizontal = "prefix+s"
split_vertical = "prefix+v"
tab_picker = "prefix+t"

[theme]
auto_switch = false
name = "terminal"

[theme.custom]
accent = "gray"
active_row_bg = "#222222"
pane_active_border = "gray"
pane_inactive_border = "darkgray"
tab_active_bg = "#000000"
tab_active_fg = "white"
tab_inactive_bg = "#000000"
tab_inactive_fg = "darkgray"

[ui]
agent_panel_sort = "spaces"
confirm_close = true
detach_effect = "matrix"
detach_effect_ms = 800
hide_tab_bar_when_single_tab = false
hide_tab_bar_with_tree_sidebar = true
mobile_width_threshold = 68
pane_borders = true
pane_gaps = false
pane_outer_borders = false
pane_scrollbars = false
prefix_hint = false
prompt_new_tab_name = false
prompt_new_workspace_name = false
show_agent_labels_on_pane_borders = false
sidebar_collapsed_mode = "hidden"
tab_bar_position = "bottom"

[ui.sidebar]
layout = "tree"
menu_button = false
new_button = false

[ui.sidebar.agents]
rows = [["state_icon", "machine", { fg = "#bbbbbb", token = "workspace" }, "spacer", "tab"]]

[ui.sidebar.machines]
agent_token = "icon"
hide_agents_when_collapsed = true

[ui.sidebar.machines.labels.andromeda]
icon = " "
name = "andromeda"

[ui.sidebar.machines.labels.local]
icon = " "
name = "mbp"

[ui.sidebar.machines.labels.work]
icon = "󰃖 "
name = "work"

[ui.sidebar.spaces]
rows = [["workspace", "git_status"]]

[ui.sidebar.tabs]
guides = "indent"
rows = [["state_icon", "tab", "spacer", "agent"]]

[ui.sound]
enabled = true

[ui.toast]
delivery = "off"
