vim.diagnostic.config({ signs = false })

-- Server defaults come from nvim-lspconfig; after/lsp/ holds the overrides.
vim.pack.add({ "https://github.com/neovim/nvim-lspconfig" })

vim.lsp.enable({
	"bashls",
	"clangd",
	"gopls",
	"golangci_lint_ls",
	"lua_ls",
	"stylua",
	"taplo",
	"zizmor",
	"jsonls",
	"nixd",
	"rust_analyzer",
	"yamlls",
	"buf_ls",
	"basedpyright",
	"ruff",
	"harper_ls",
	"gdscript",
	"zls",
	"solidity_ls",
})

-- jdtls builds its command in a function, which vim.lsp.enable cannot check, so
-- without this a missing jdtls fails on every Java file.
if vim.fn.executable("jdtls") == 1 then
	vim.lsp.enable("jdtls")
end

-- Servers that only exist when a feature installs them.
-- Generated by home/packages/shell/neovim.nix.
pcall(require, "lsp-features")
