vim.diagnostic.config({ signs = false })

-- Server defaults come from nvim-lspconfig; after/lsp/ holds the overrides.
vim.pack.add({ "https://github.com/neovim/nvim-lspconfig" })

-- The servers this machine installs, generated by home/packages/shell/neovim.nix.
pcall(require, "lsp-servers")
