
set  -g default-terminal "screen"
set  -g base-index      1
setw -g pane-base-index 1





set -g status-keys vi
set -g mode-keys   vi







set  -g mouse             on
set  -g focus-events      on
setw -g aggressive-resize on
setw -g clock-mode-style  12
set  -s escape-time       0
set  -g history-limit     10000

set -g extended-keys on
set -as terminal-features ',*ghostty*:extkeys:progressbar'
set -g extended-keys-format csi-u

bind -r -N "Move window to the left" \
  '<' swap-window -d -t '{previous}'

bind -r -N "Move window to the right" \
  '>' swap-window -d -t '{next}'

bind -N "Select the previous window" C-p select-window -p
bind -N "Select the previous window" p select-window -p
bind -N "Select the next window" C-n select-window -n
bind -N "Select the next window" n select-window -n

bind -N "Select pane to the left of the active pane" C-h select-pane -L
bind -N "Select pane below the active pane" C-j select-pane -D
bind -N "Select pane above the active pane" C-k select-pane -U
bind -N "Select pane to the right of the active pane" C-l select-pane -R
bind -N "Select pane to the left of the active pane" h select-pane -L
bind -N "Select pane below the active pane" j select-pane -D
bind -N "Select pane above the active pane" k select-pane -U
bind -N "Select pane to the right of the active pane" l select-pane -R

bind -r -N "Resize the pane left by 5" \
  H resize-pane -L 5

bind -r -N "Resize the pane down by 5" \
  J resize-pane -D 5

bind -r -N "Resize the pane up by 5" \
  K resize-pane -U 5

bind -r -N "Resize the pane right by 5" \
  L resize-pane -R 5

bind r source-file ~/.config/tmux/tmux.conf \; display " Config reloaded!"

bind -N "Select last window" \
  tab last-window

set -g renumber-windows on
set -g allow-rename off

unbind -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-no-clear

# Theme
set -g status-justify left
set -g status-style "bg=default bold"

set -g status-left " #S "
set -g status-left-style "fg=green"
set -g status-left-length 20

set -g status-right "#{?#{SSH_CONNECTION},#[fg=brightblue#,bold] #{user}@#H #[default],}"
set -g window-status-style "#{?#{==:#{client_theme},light},fg=colour8#,bg=default#,dim,fg=colour8#,bg=default}"
set -g window-status-current-style "fg=terminal"

set -g pane-active-border-style "bold fg=#858585"
set -g pane-border-style "fg=colour234"
set -g allow-passthrough on

# TODO: is this still needed with ghostty?
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set-option -sa terminal-overrides ",xterm*:Tc"

set -g message-style 'fg=yellow bg=black bold'

bind-key "s" run-shell "sesh connect \"$(
  sesh list --icons | fzf --tmux 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list --icons -t)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list --icons -c)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list --icons -z)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}' \
    -- --ansi
)\""
