# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
      kernelModules = [ ];
      luks.devices = {
        # Enable swap on luks
        "luks-526c0b0d-5740-42c8-ae76-4f67ca1e1a23" = {
          device = "/dev/nvme0n1p3";
          keyFile = "/crypto_keyfile.bin";
        };
      };
      secrets = {
        "/crypto_keyfile.bin" = null;
      };
    };
    blacklistedKernelModules = [ "rtsx_pci" "rtsx_pci_sdmcc" ];
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/2ecc0a40-dde7-4823-bf0f-ab00ee3f7985";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-667ba30f-c3a9-4f3c-b210-ee8a5b8c4076".device = "/dev/disk/by-uuid/667ba30f-c3a9-4f3c-b210-ee8a5b8c4076";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/C074-9DE6";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/b5e8f8cf-d78b-4e83-b0c1-f96539f14547"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.enableIPv6 = false;
  # networking.networkmanager.enable = true;
  # networking.networkmanager.insertNameservers = [ "8.8.8.8" "8.8.4.4" ];
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  networking = {
    hostName = "xps";
    useDHCP = false;
    wireless.enable = true;
  };

  systemd.network = {
    enable = true;
    networks.home = {
      matchConfig.Name = "wlp2s0";
      networkConfig = {
        DHCP = "yes";
        DNSSEC = "yes";
        DNSOverTLS = "yes";
        DNS = [ "1.1.1.1" "1.0.0.1" ];
        IPv6AcceptRA = false;
      };
      linkConfig.RequiredForOnline = "routable";
    };
    wait-online = {
      anyInterface = true;
      timeout = 5;
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";

  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    bluetooth = {
      enable = true;
      settings = {
        General = {
          Enable = "Source,Sink,Media,Socket";
        };
      };
    };
    graphics.enable = true;
    graphics.enable32Bit = true;
  };
}
